mental_db = {"headache": {"keywords":[],
    "reasons":[],
    "dos":[],
    "dont_s":[],
    "home_remedies":[],
    "medicines":[],
    "app_one_liner":[],
    "problem_score": 10}, "anxeity": {"keywords":[],
    "reasons":[],
    "dos":[],
    "dont_s":[],
    "home_remedies":[],
    "medicines":[],
    "app_one_liner":[],
    "problem_score": 10}}